### ISSUE TITLE
Export contract version as py variable

### ISSUE THREAD

**Issue by noandrea** [autonity/autonity.py#29]
The update-abi scripts writes the git version of the contract on a text file,
and the build process bundles the abi files in the python package. 
 
Expose these info so they can be used by third party app.

It will introduce 2 new exported functions:
- `def get_autonity_contract_version() -> str:`
- `def get_autonity_contract_abi_path() -> str:`

### Use case

The `aut` client introduces a new sub-command group `utils` or `info` with the following commands
- `autonity-contract-version` the permalink to the contract github url using the `contract_git_commit_hash`
- `autonity-contract-abi` the path to the abi file embedded in the `autonity.py` library 
- `autonity-contract-address `the contract address (since it doesn't change)

It should also add the exact sequence of commands that are used to generate the abi since the abi keys are sorted before the checksum is calculated

**Comment by aiman** [comment]
strangely, moving to Done column did not close the issue
