### ISSUE TITLE
Generate all contact bindings automatically

### ISSUE THREAD

**Issue by aiman** [autonity/autonity.py#73]
Previously, only Autonity and Liquid contracts had bindings that were manually maintained. With the new pyabigen tool, we can now generate bindings for all contracts starting from the Tiber upgrade.

This will add new bindings for:

- Accountability
- ACU
- Inflation Controller
- Liquid Logic
- Omission Accountability
- Oracle
- Stabilization
- Supply Control
- Upgrade Manager

However, this will break the interface for the Autonity bindings.

**Comment by szemate** [comment]
Resolved by #59.
